### ISSUE TITLE
Deserialization exception for model with ManyToOneRel

### ISSUE THREAD

**Issue by groundupnews** [radiac/django-tagulous#14]
I'm using Django 1.8.7 and have a model with several tagulous fields and with ForeignKeys pointing to it from other models.

When I serialize it (Article) like so:
`data = serializers.serialize("xml", Article.objects.published()[:1])`

And then deserialize it (test code):

```
for obj in serializers.deserialize("xml", data):
    type(obj.object)
```

This exception is thrown:

```

File " ... /tagulous/models/tagged.py", line 414, in _detag_to_serializable
    clone_field.contribute_to_class(FakeTaggedModel, field.name)
AttributeError: 'ManyToOneRel' object has no attribute 'contribute_to_class
```

If I comment out all references to Article in models that use it as a ForeignKey, the deserialization proceeds without throwing an Exception. It is when the ManyToOneRel fields are encountered that the exception occurs because these do not appear to have "contribute_to_class" attributes.

I can supply more information upon request, but the model is large and I'm hoping this is enough to reproduce the error. (Exception trace below.)

Thanks (I'm otherwise finding tagulous excellent).

EXCEPTION TRACE

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/nathan/workspace/gu/groundup/test.py", line 10, in <module>
    for obj in serializers.deserialize("xml", data):
  File "/home/nathan/workspace/gu/lib/python3.4/site-packages/django/core/serializers/xml_serializer.py", line 169, in __next__
    return self._handle_object(node)
  File "/home/nathan/workspace/gu/lib/python3.4/site-packages/tagulous/serializers/xml_serializer.py", line 63, in _handle_object
    obj = super(Deserializer, self)._handle_object(node)
  File "/home/nathan/workspace/gu/lib/python3.4/site-packages/django/core/serializers/xml_serializer.py", line 178, in _handle_object
    Model = self._get_model_from_node(node, "model")
  File "/home/nathan/workspace/gu/lib/python3.4/site-packages/tagulous/serializers/xml_serializer.py", line 74, in _get_model_from_node
    Model = RealModel._detag_to_serializable()
  File "/home/nathan/workspace/gu/lib/python3.4/site-packages/tagulous/models/tagged.py", line 413, in _detag_to_serializable
    clone_field.contribute_to_class(FakeTaggedModel, field.name)
AttributeError: 'ManyToOneRel' object has no attribute 'contribute_to_class
``
```

**Comment by etjones** [comment]
+1.  I've run into this while trying to run `manage.py loaddata  <database_dump.json>`  

The logic in `tagulous.models.tagged.FakeTaggedModel._retag_to_original()`  handles ManyToMany fields, but seems to choke on the ManyToOneRel fields in my model.  I've been looking for a workaround, but haven't figured anything out yet.  

Like groundup said- Tagulous is otherwise a really spectacular piece of work.

**Comment by proSingularity** [comment]
+1. The error prevents me from using django-reversions. I have a model that has two TagField. In the admin when I choose an instance of my model with the TagFields, then on history, and then choose any of the history entries, I get about the same error as groundupnews. I'm running django 1.9.5.

**Comment by etjones** [comment]
I'm happy to make a fix for this, but I'm not totally clear on what these _detag/_retag methods are doing.  @radiac , it looks like this FakeTaggedModel class was a workaround for some de/serialization issues with the way Tagulous' tags live in separate tables from their model instances.  Any idea how we ought to handle Relations in this process?

**Comment by radiac** [comment]
Thanks for the bug reports and kind words, and my apologies that I haven't had a chance to do anything about this issue in the time since it was opened.

You're right - this is part of the workaround for de/serialisation. As you say, tags live in a separate table but serialised tags need to be stored as string/list values, rather than FK references. Tagulous does this by replacing a `TaggedModel` class with a `FakeTaggedModel` which the standard serialisers can work with, then reversing it when deserialising.

Quick overview: the Tagulous serialisers [patch themselves](https://github.com/radiac/django-tagulous/blob/master/tagulous/serializers/python.py#L24) using [this function](https://github.com/radiac/django-tagulous/blob/master/tagulous/serializers/base.py#L60), so they can switch a `TaggedModel` class for a `FakeTaggedModel` equivalent using [_detag](https://github.com/radiac/django-tagulous/blob/master/tagulous/models/tagged.py#L359). This [switches out](https://github.com/radiac/django-tagulous/blob/master/tagulous/models/tagged.py#L405) the FK field for a plain field so the [serializer](https://github.com/radiac/django-tagulous/blob/master/tagulous/serializers/base.py#L12) can store the values rather than FK references. Deserialisation does the opposite - again, the [patch](https://github.com/radiac/django-tagulous/blob/master/tagulous/serializers/base.py#L60) calls _detag which returns a `FakeTaggedModel`, so the [object deserialiser](https://github.com/radiac/django-tagulous/blob/master/tagulous/serializers/base.py#L32) then has access to the [_retag](https://github.com/radiac/django-tagulous/blob/master/tagulous/models/tagged.py#L377) method. That returns an instance of the correct class, by passing all non-M2M data across into the constructor (including tag fields - tagged model constructors support strings or lists for tag fields).

I think this means we can just ignore a `ManyToOneRel` altogether. Without doing any testing I'm thinking because it's the reverse of an FK it won't show up in serialised output, and there won't be anything to deserialise. If so, that _should_ be a pretty simple fix - change [387](https://github.com/radiac/django-tagulous/blob/master/tagulous/models/tagged.py#L387) to:

    if isinstance(field, ManyToOneRel):
        continue
    elif isinstance(field, TagField) or not (

and [411](https://github.com/radiac/django-tagulous/blob/master/tagulous/models/tagged.py#L411) to:

    elif isinstance(field, ManyToOneRel):
        continue
    else:

However, like I say, that's totally untested! :)  I'll try to take a proper look later today.

**Comment by etjones** [comment]
Thanks for that writeup, Richard; that's super helpful.  I ran into problems when I tried to just skip the ManyToOneRel fields the other day, but this background should let me find a workaround.  I'll see if I can solve this and submit a PR this weekend.

**Comment by m-thielen** [comment]
Any news about this issue?

**Comment by nutrina** [comment]
@etjones : Hello, I have run into the same problem as you when running `manage.py loaddata <database_dump.json>`. Have you been able to fix this?
