### ISSUE TITLE
Select2 initialiser broken with Django 4.1

### ISSUE THREAD

**Issue by jedie** [radiac/django-tagulous#179]
It seems that `select2-4.js` code is not compatible with Django 4.1:

![grafik](https://user-images.githubusercontent.com/71315/235852035-96038147-36c6-4757-9a85-cb5b94dfd90d.png)

**Comment by engrimran7** [comment]
I am also wandering to get help using latest tagulous with django 4.2 and python 3.10 i am copying and parsing all the fields in a form to tagsfield as tags code is working fine tags are getting saved and associated to posts also and also can see the association of posts in tagulous admin interface but the issue is tagfields of posts remain empty no tags at all even if i try to edit the post it shows no tags bit admin panel shows tags.

And i am also facing exactly the same issue with taggit too.

**Comment by engrimran7** [comment]
I am also wandering to get help using latest tagulous with django 4.2 and python 3.10 i am copying and parsing all the fields in a form to tagsfield as tags code is working fine tags are getting saved and associated to posts also and also can see the association of posts in tagulous admin interface but the issue is tagfields of posts remain empty no tags at all even if i try to edit the post it shows no tags bit admin panel shows tags.

And i am also facing exactly the same issue with taggit too.

**Comment by radiac** [comment]
There have been some significant changes to the Django template system, I suspect that's something to do with it. I'm hoping to get some time next week to take a look at what has gone wrong.

**Comment by radiac** [comment]
Brilliant, thanks for the detective work, that'll help! Hoping to get to this next week.
