### ISSUE TITLE
Set TagTree parent without slashes

### ISSUE THREAD

**Issue by KhanMaytok** [radiac/django-tagulous#38]
I would like set the parent of a tag without slashes, instead with a select box. For example dont use this:

![alt text](https://i.gyazo.com/22f6d940a8cfc9dc7b81a3ac7f22ffe8.png)

And use it:

![alt text](https://i.gyazo.com/2bd7c958158c8d50513a06c9597a74c9.png)

**Comment by radiac** [comment]
The standard `TagTreeModel` needs the parent to be part of the tag name, otherwise it's not going to be possible to have the same tag under different parents, eg `Photos/Cat` and `Videos/Cat`

If you want to keep that and everything else about the `TagTreeModel` the same, and just change how the form looks in the admin, you could probably hack the modeladmin for that tag model to use a different form (with its own name and parent fields) and then split or merge the fields when showing and saving the form.

The other option would be to write a custom tag model to do this - take a look at how the `TagTreeModel` subclasses the base tree model: https://github.com/radiac/django-tagulous/blob/develop/tagulous/models/models.py#L817 - however, if you don't store the tag names with slashes, tagulous won't be able to help you render them.

Ultimately if neither of these options work for you, you may end up deciding that Tagulous isn't the best choice for this, and you'd be better off using something like MPTT with a standard M2M instead of a TagField.
