### ISSUE TITLE
TagRelatedManager indexing support

### ISSUE THREAD

**Issue by panpanick** [radiac/django-tagulous#66]
Something I would like is indexing support for the TagRelatedManager. This is for a case where a slug is passed to a view, and after grabbing the correct tags based on the slug, I want to also get the name of that respective tag. Like this
```
lang_name = Game.approved.filter(language__slug=lang_slug).first().language[lang_slug].name
```

**Comment by radiac** [comment]
Thanks for the suggestion! I think you should be able to accomplish the same thing with:

```
lang_name = Game.approved.filter(language__slug=lang_slug).first().language.tag_model.objects.get(slug=lang_slug).name
```

It's a bit more of a mouthful, but as Tagulous tries to treat the original unslugified tag name as the canonical version rather than the slug, I think it could cause confusion if we use the slug as the index key instead of the name.  I think there's actually an understandability/maintenance bonus for explicitly matching on the slug as above. That said, if it's something you're doing a lot then you could create your own manager and assign it?

Because of this and as it's possible without too much extra code, I'm not sure its a great fit for a core feature at the moment. I'll therefore close this ticket for now, but if there's more interest in the future this may be something we can revisit. Thanks again!
