### ISSUE TITLE
JS error in Django 2.2+ when using ModelAdmin.autocomplete_fields

### ISSUE THREAD

**Issue by jeffbowen** [radiac/django-tagulous#76]
I have a ModelAdmin which contains a couple of TagFields fields and a ForeignKey field (among others). In Django 2.2+ (issue not present in Django 2.1.11), if I include that ForeignKey field in the ModelAdmin's `autocomplete_fields`, I get JavaScript errors related to both fields:

`Error: Option 'ajax' is not allowed for Select2 when attached to a <select> element.`
in `tagulous/lib/select2-3/select2.min.js`

and

`TypeError: $el.select2 is not a function. (In '$el.select2(args)', '$el.select2' is undefined)`
in `admin/js/vendor/jquery/jquery.js`

**Comment by tq0** [comment]
I came across the same problem and traced it down to the order of javascript resources in generated HTML. The `media` property in admin form is generated as a result of merging `media` of all widgets within the form, but the algorithm has changed significantly from Django [2.1](https://github.com/django/django/blob/2.1.11/django/forms/widgets.py) to [2.2](https://github.com/django/django/blob/2.2.4/django/forms/widgets.py).

**Comment by radiac** [comment]
Thanks for flagging this. I think the best solution is to add a new select2 adaptor so Tagulous can use the same version that ships with Django and we can drop the extra media requirements - it'll take me a while to get onto this, so if anyone finds any hacks to get the current version working in the meantime do let me know.

**Comment by mosessoh** [comment]
Hi @radiac, would you be able to point me in the right direction on how we could write a new select2 adapter? I gave it a go last weekend, but couldn't make much headway. 

- Do we need to change the class of `TagWidgetBase` in `forms.py` to `forms.SelectMultiple` since Select2 now works on <select> elements - or do you think it's possible to solve this issue just by writing a new adapter?

Would be happy to give it another go with your thoughts/guidance.  

Stuff I've tried (for anyone else working on similar problems):
- Isolating select2 v4 from Tagulous' select2: https://stackoverflow.com/questions/36785006/how-can-select2-3-5-and-4-0-conflicts-be-resolved. But because select2 v4 is relied upon by Django Admin in multiple places, changing `.select2()`  to .`<prefix>select2()` doesn't work, and it's difficult to isolate select2 v3.5 since it relies on globals.

- Relatedly, the included select2 v4 in Django Admin doesn't create the global `window.Select2` (it's more isolated) so the current adapter is failing, and the monkey patching is failing as well.

**Comment by mosessoh** [comment]
To the original issue from @jeffbowen, I managed to get around both errors by substituting `jQuery` at the end of the `select2-3.js` adapter to `django.jQuery`, and upgrading select2.js from v.3.5.2 (tagulous' version) to `select2.full.js` v4.0.x which has packages for backward compatibility.

But I couldn't get the AdminWidget to return values. @radiac if you have any ideas as to why that might be, appreciate your thoughts.
