### ISSUE TITLE
RIP Tagulous

### ISSUE THREAD

**Issue by paconius** [radiac/django-tagulous#90]
Given that this project uses the Select2 version from 6 years ago and doesn't look like it will be updated for Django 3.0, I surmise that this is a dead project.

Since tagging + non-admin built-in javascript widget + autocomplete is still a highly relevant feature set, what are people now using to implement this? It looks like django-taggit is still alive. I am curious about recommendations for a good way to extend this to mimic all of the old features of Tagulous. What are people using these days?

**Comment by radiac** [comment]
The project is not dead. You may have noticed that I last pushed a large commit to develop 24 days ago. The task I'm working on now is adding a select2 v4 adaptor, but it's hard work because their docs don't match the code.

As you'll see from the roadmap, once select2 v4 is supported, I'll push out a 1.0 release supporting <2.2, then drop support for that in order to support dj3+, as per their instructions.

However, given I'm working a full time job while also doing childcare 3 days a week while my wife is working on covid wards in full PPE during a global pandemic, I'm sure you'll understand that this may take me a few more days.

Given this is an open source project, contributions are of course always welcome.

**Comment by paconius** [comment]
Okay. Thanks for the update. I was able to drop in django-select2 to implement tags without too much trouble. The only thing it doesn't have is tab completion of tags (you have to use commas) -- so if you keep the tab completion functionality you have a change to be best-in-class once again.
